// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQps0r8Ld6yn_bPABfWap6lRr9zMEFdKs',
    appId: '1:599628355040:web:5caeeebe2fade5af8e4785',
    messagingSenderId: '599628355040',
    projectId: 'iostest-93043',
    authDomain: 'iostest-93043.firebaseapp.com',
    storageBucket: 'iostest-93043.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL2P4jdg5FLsb-jFMB2t0qrtFnhsaJ388',
    appId: '1:599628355040:android:a32e9838bc9b8bb68e4785',
    messagingSenderId: '599628355040',
    projectId: 'iostest-93043',
    storageBucket: 'iostest-93043.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuRKYssjxiCfBLl0OBJ9zY-lXXRa6FbfM',
    appId: '1:599628355040:ios:8fb6e09c9dd13ae18e4785',
    messagingSenderId: '599628355040',
    projectId: 'iostest-93043',
    storageBucket: 'iostest-93043.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuRKYssjxiCfBLl0OBJ9zY-lXXRa6FbfM',
    appId: '1:599628355040:ios:8fb6e09c9dd13ae18e4785',
    messagingSenderId: '599628355040',
    projectId: 'iostest-93043',
    storageBucket: 'iostest-93043.firebasestorage.app',
    iosBundleId: 'com.example.tp5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQps0r8Ld6yn_bPABfWap6lRr9zMEFdKs',
    appId: '1:599628355040:web:20181428b729336b8e4785',
    messagingSenderId: '599628355040',
    projectId: 'iostest-93043',
    authDomain: 'iostest-93043.firebaseapp.com',
    storageBucket: 'iostest-93043.firebasestorage.app',
  );

}